name: C/C++ AppImage
on:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'src/**'
      - 'ci/**'
      - '.github/workflows/linux.yml'
  pull_request:
    paths:
      - 'CMakeLists.txt'
      - 'src/**'
      - 'ci/**'
      - '.github/workflows/linux.yml'


jobs:
  build-appimage:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-default qtdeclarative5-dev cmake
      - name: configure
        run: cmake -H. build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
      - name: build
        run: cmake --build build
      - name: install
        run: |
          cd build
          make install DESTDIR=../AppDir
          cd ../
      - name: Build AppImage
        run: |
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/share/applications/*.desktop -appimage
          mv HexBitAnalysis*.AppImage HexBitAnalysis-x86_64.AppImage
      - uses: actions/upload-artifact@v2
        with:
          name: HexBitAnalysis-${{ github.run_id }}-linux
          path: HexBitAnalysis*.AppImage
      # tag 上传Release
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: HexBitAnalysis-x86_64.AppImage
          asset_name: HexBitAnalysis-${{ github.ref_name }}-linux.AppImage
          tag: ${{ github.ref }}
          overwrite: true
